fix(9): adding 24 hrs limit to password renew link
yann-yinn/adonis-starter pull request #15
Opened 2021-09-27 16:39 UTC by HugoLd

Ici une date trop ancienne 
![image](https://user-images.githubusercontent.com/26521848/134950195-26adaa6a-2da5-4a5e-9e5d-bb0a8defb872.png)

Ici une date valable 
![image](https://user-images.githubusercontent.com/26521848/134950258-5e133c5a-b84b-4543-8da2-d78b700fb17d.png)

2021-09-27 16:40 UTC, HugoLd commented on app/Controllers/Http/ForgotPasswordController.ts
> +    return view.render("pages/ForgotPasswordCheckYourInbox", {
rien à voir avec ma PR mais c'était foireux je le passe en même temps

2021-09-27 16:47 UTC, yann-yinn requested changes

2021-09-27 16:47 UTC, yann-yinn commented on app/Controllers/Http/ForgotPasswordController.ts
> +      return view.render('errors/not-found')
Pas besoin de ça je pense: le findOrFail() contenu dans le findById() va automatiquement faire un status de réponse 404, et celui s'occupera d'afficher la page 404. Donc juste le `await VerificationProcedureService.findById(params.id)).createdAt.diffNow("hours").hours > -24){` est suffisant pour gérer le cas de la vue error 404

2021-09-27 17:49 UTC, yann-yinn commented on app/Controllers/Http/ForgotPasswordController.ts
> +      return view.render('errors/not-found')
plutôt faire un response.notFound() ici que d'appeler le template directement, c'est le handler d'exception HTTP app/Exceptions/Handler.ts qui gerera, comme c'est le cas ailleurs

2021-09-28 09:16 UTC, yann-yinn commented on app/Controllers/Http/ForgotPasswordController.ts
> +      return view.render('errors/not-found')
au passage, si on trouve un enregistrement de plus de 24h, autant faire un "delete" en même temps que le response.notFound(), comme ça on clean la database en même temps à cette occasion

2021-09-29 08:00 UTC, merged